#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

# If you want to allow non-ASCII filenames set this variable to true.
allownonascii=$(git config --type=bool hooks.allownonascii)

# Redirect output to stderr.
exec 1>&2

# Cross platform projects tend to avoid non-ASCII filenames; prevent
# them from being added to the repository. We exploit the fact that the
# printable range starts at the space character and ends with tilde.
if [ "$allownonascii" != "true" ] &&
	# Note that the use of brackets around a tr range is ok here, (it's
	# even required, for portability to Solaris 10's /usr/bin/tr), since
	# the square bracket bytes happen to fall in the designated range.
	test $(git diff --cached --name-only --diff-filter=A -z $against |
	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
then
	cat <<\EOF
Error: Attempt to add a non-ASCII file name.

This can cause problems if you want to work with people on other platforms.

To be portable it is advisable to rename the file.

If you know what you are doing you can disable this check using:

  git config hooks.allownonascii true
EOF
	exit 1
fi

RED='\033[0;31m'
ORANGE='\033[0;33m]'
GREEN='\033[0;32m]'
NC='\033[0m' # No Color

[ -r ../PostSomething-api.Tests/PostSomething-api.Tests.csproj ] || { printf "${RED}ERROR${NC}: You must clone the parent repository to commit new changes.\n" && exit 1; }
dotnet test ../PostSomething-api.Tests/PostSomething-api.Tests.csproj || exit 1

dotnet format ../PostSomething.sln --verify-no-changes || { printf "${RED}ERROR${NC}: Formatting requirements not met. Please run dotnet format.\n" && exit 1 ; }

###############################
## Check Code Coverage (BASH) #
###############################

TARGET_COVERAGE=90

COVERAGE_OUTPUT=`dotnet test ../PostSomething-api.Tests -p:CollectCoverage=true -p:Exclude="[*]PostSomething-api.Models.*%2c[*]PostSomething_api.Database.*%2c[*]PostSomething_api.Migrations.*%2c[*]PostSomething_api.Repositories.*%2c[*]Program" | grep "| PostSomething-api |"`

LINE_COVERAGE=`echo $COVERAGE_OUTPUT | awk -F '|' '{print $3}' | grep -o "[[:digit:]]\+\(\.[[:digit:]]\+\)*"`
BRANCH_COVERAGE=`echo $COVERAGE_OUTPUT | awk -F '|' '{print $4}' | grep -o "[[:digit:]]\+\(\.[[:digit:]]\+\)*"`
METHOD_COVERAGE=`echo $COVERAGE_OUTPUT | awk -F '|' '{print $5}' | grep -o "[[:digit:]]\+\(\.[[:digit:]]\+\)*"`

awk -v TARGET_COVERAGE=$TARGET_COVERAGE -v LINE_COVERAGE=$LINE_COVERAGE 'BEGIN {exit !(LINE_COVERAGE >= TARGET_COVERAGE)}' && echo "INFO: Line Coverage met" || echo "WARN: Line coverage not met"
awk -v TARGET_COVERAGE=$TARGET_COVERAGE -v BRANCH_COVERAGE=$BRANCH_COVERAGE 'BEGIN {exit !(BRANCH_COVERAGE >= TARGET_COVERAGE)}' && echo "INFO: Branch Coverage met" || echo "WARN: Branch coverage not met"
awk -v TARGET_COVERAGE=$TARGET_COVERAGE -v METHOD_COVERAGE=$METHOD_COVERAGE 'BEGIN {exit !(METHOD_COVERAGE >= TARGET_COVERAGE)}' && echo "INFO: Method Coverage met" || echo "WARN: Method coverage not met"

awk -v TARGET_COVERAGE=$TARGET_COVERAGE -v LINE_COVERAGE=$LINE_COVERAGE -v BRANCH_COVERAGE=$BRANCH_COVERAGE -v METHOD_COVERAGE=$METHOD_COVERAGE 'BEGIN {exit !(LINE_COVERAGE >= TARGET_COVERAGE && BRANCH_COVERAGE >= TARGET_COVERAGE && METHOD_COVERAGE >= TARGET_COVERAGE)}' || { echo "ERROR: Code coverage not met." && exit 1 ; }

###############################
## Check Code Coverage (BASH) #
###############################

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
